# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontDoorNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_content', models.TextField()),
                ('news_creation_date', models.DateTimeField(auto_now_add=True)),
                ('news_last_updated', models.DateTimeField(auto_now=True)),
                ('news_published', models.BooleanField(default=False)),
                ('news_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'front_door_news',
                'verbose_name_plural': 'Front Door News',
            },
        ),
    ]
