# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontdoor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_subject', models.CharField(max_length=100)),
                ('feedback_body', models.TextField()),
                ('feedback_submitted_on', models.DateTimeField(auto_now_add=True)),
                ('feedback_read', models.BooleanField(default=False)),
                ('feedback_responded_to', models.BooleanField(default=False)),
                ('feedback_submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Feedback',
                'db_table': 'feedback',
                'managed': True,
            },
        ),
    ]
