# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteapisettings',
            name='wow_oauth_user_profile_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
