# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAPISettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wow_api_key', models.CharField(max_length=100)),
                ('wow_api_secret', models.CharField(max_length=100)),
                ('wow_api_character_url_fields', models.CharField(max_length=200)),
                ('wow_api_base_url', models.URLField()),
                ('wow_api_character_image_base_url', models.URLField()),
            ],
            options={
                'db_table': 'website_api_settings',
                'managed': True,
                'verbose_name_plural': 'Website API Settings',
            },
        ),
    ]
