# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guilds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('guild_faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Factions')),
                ('guild_realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Realms')),
            ],
            options={
                'db_table': 'guilds',
                'managed': True,
                'verbose_name_plural': 'Player Guilds',
            },
        ),
    ]
