# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guilds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_name', models.CharField(max_length=255)),
                ('guild_information', models.TextField()),
                ('guild_battlenet_website', models.URLField(blank=True, null=True)),
                ('guild_external_website', models.URLField(blank=True, null=True)),
                ('guild_wow_progress_link', models.URLField(blank=True, null=True)),
                ('guild_warcraft_logs_link', models.URLField(blank=True, null=True)),
                ('guild_world_of_logs_link', models.URLField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recruiting', models.BooleanField(default=False)),
                ('guild_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('guild_faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Factions')),
                ('guild_realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Realms')),
            ],
            options={
                'ordering': ['guild_realm'],
                'db_table': 'guilds',
                'managed': True,
                'verbose_name_plural': 'Player Guilds',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiting_levels', models.CharField(max_length=100)),
                ('recruitment_title', models.CharField(max_length=200)),
                ('recruitment_post', models.TextField()),
                ('is_post_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('guild_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Guilds')),
                ('recruiting_classes', models.ManyToManyField(to='players.Classes')),
            ],
            options={
                'db_table': 'recruitment_posts',
                'managed': True,
                'verbose_name_plural': 'Recruitment Postings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='guilds',
            unique_together=set([('guild_name', 'guild_realm', 'guild_faction')]),
        ),
    ]
