# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guilds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_name', models.CharField(max_length=255)),
                ('guild_realm', models.CharField(max_length=50)),
                ('guild_battlegroup', models.CharField(max_length=50)),
                ('guild_level', models.IntegerField()),
                ('guild_faction', models.IntegerField()),
                ('load_date', models.DateField()),
            ],
            options={
                'db_table': 'guilds',
                'managed': True,
                'verbose_name_plural': 'Player Guilds',
            },
        ),
    ]
