# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0002_auto_20170320_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilds',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
