# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0003_guilds_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilds',
            name='guild_battlenet_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guilds',
            name='guild_external_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
