# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0004_auto_20170419_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guildmanagers',
            options={'managed': True, 'ordering': ['guild_id'], 'verbose_name_plural': 'Guild Managers'},
        ),
    ]
