# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0004_auto_20170320_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilds',
            name='guild_warcraft_logs_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guilds',
            name='guild_world_of_logs_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guilds',
            name='guild_wow_progress_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
