# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20170320_1440'),
        ('guilds', '0005_auto_20170320_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiting_levels', models.CharField(max_length=100)),
                ('recruitment_title', models.CharField(max_length=200)),
                ('recruitment_post', models.TextField()),
                ('is_post_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Recruitment Postings',
                'db_table': 'recruitment_posts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='guilds',
            name='is_recruiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitmentposts',
            name='guild_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Guilds'),
        ),
        migrations.AddField(
            model_name='recruitmentposts',
            name='recruiting_classes',
            field=models.ManyToManyField(to='players.Classes'),
        ),
    ]
