# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20170320_1440'),
        ('guilds', '0006_auto_20170320_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentposts',
            name='guild_faction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='players.Factions'),
            preserve_default=False,
        ),
    ]
