# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0007_recruitmentposts_guild_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilds',
            name='guild_information',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
