# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0007_auto_20170422_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiddays',
            name='raid_day',
            field=models.CharField(max_length=10),
        ),
    ]
