# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0008_auto_20170422_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidtimes',
            name='raid_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='raidtimes',
            name='raid_start_time',
            field=models.TimeField(),
        ),
    ]
