# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0008_guilds_guild_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guilds',
            name='guild_managers',
        ),
    ]
