# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0009_auto_20170422_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentposts',
            name='raid_days',
            field=models.ManyToManyField(to='guilds.RaidDays'),
        ),
    ]
