# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0009_remove_guilds_guild_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guilds',
            options={'managed': True, 'ordering': ['guild_realm', 'guild_faction'], 'verbose_name_plural': 'Player Guilds'},
        ),
    ]
