# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0010_auto_20170422_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raidtimes',
            old_name='raid_end_time',
            new_name='time_value',
        ),
        migrations.RemoveField(
            model_name='raidtimes',
            name='raid_start_time',
        ),
    ]
