# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 18:14
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0024_auto_20170321_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guilds',
            name='guild_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=('guild_name', 'guild_realm', 'guild_faction'), unique=True),
        ),
    ]
