# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0032_remove_guilds_guild_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentposts',
            name='recruiting_classes',
        ),
    ]
