# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0034_auto_20170323_1941'),
        ('guilds', '0035_remove_recruitmentposts_guild_faction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guilds',
            unique_together=set([('guild_name', 'guild_realm', 'guild_faction')]),
        ),
    ]
