# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 14:45
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleNetIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_net_id', models.CharField(max_length=50)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Battle Net IDs',
                'db_table': 'battle_net_ids',
            },
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=255)),
                ('character_level', models.IntegerField()),
                ('character_ilevel', models.IntegerField()),
                ('character_ilevel_equipped', models.IntegerField()),
                ('character_head', models.CharField(max_length=50)),
                ('character_neck', models.CharField(max_length=50)),
                ('character_shoulder', models.CharField(max_length=50)),
                ('character_back', models.CharField(max_length=50)),
                ('character_chest', models.CharField(max_length=50)),
                ('character_wrist', models.CharField(max_length=50)),
                ('character_hands', models.CharField(max_length=50)),
                ('character_waist', models.CharField(max_length=50)),
                ('character_legs', models.CharField(max_length=50)),
                ('character_feet', models.CharField(max_length=50)),
                ('character_finger1', models.CharField(max_length=50)),
                ('character_finger2', models.CharField(max_length=50)),
                ('character_trinket1', models.CharField(max_length=50)),
                ('character_trinket2', models.CharField(max_length=50)),
                ('character_mainhand', models.CharField(db_column='character_mainHand', max_length=50)),
                ('character_offhand', models.CharField(db_column='character_offHand', max_length=50)),
                ('character_agility', models.IntegerField()),
                ('character_armor', models.IntegerField()),
                ('character_block', models.FloatField()),
                ('character_critical_strike', models.FloatField()),
                ('character_dodge', models.FloatField()),
                ('character_haste', models.FloatField()),
                ('character_health', models.IntegerField()),
                ('character_intellect', models.IntegerField()),
                ('character_leech', models.FloatField()),
                ('character_mastery', models.FloatField()),
                ('character_parry', models.FloatField()),
                ('character_power', models.IntegerField()),
                ('character_stamina', models.IntegerField()),
                ('character_strength', models.IntegerField()),
                ('character_versatility', models.IntegerField()),
                ('load_date', models.DateField()),
                ('character_battle_net_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.BattleNetIDs')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Characters',
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=50)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Character Classes',
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Factions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_id', models.IntegerField()),
                ('faction_name', models.CharField(max_length=50)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Character Factions',
                'db_table': 'factions',
            },
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField()),
                ('race_name', models.CharField(max_length=50)),
                ('race_faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Factions')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Character Races',
                'db_table': 'races',
            },
        ),
        migrations.CreateModel(
            name='Realms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_type', models.CharField(max_length=50)),
                ('realm_population', models.CharField(max_length=10)),
                ('realm_name', models.CharField(max_length=50)),
                ('realm_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='realm_name')),
                ('realm_battlegroup', models.CharField(max_length=50)),
                ('realm_locale', models.CharField(max_length=50)),
                ('realm_timezone', models.CharField(max_length=255)),
                ('realm_connected_realms', models.TextField()),
                ('load_date', models.DateField()),
            ],
            options={
                'managed': True,
                'ordering': ['realm_name'],
                'verbose_name_plural': 'Realms',
                'db_table': 'realms',
            },
        ),
        migrations.AddField(
            model_name='characters',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Classes'),
        ),
        migrations.AddField(
            model_name='characters',
            name='character_faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Factions'),
        ),
        migrations.AddField(
            model_name='characters',
            name='character_race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Races'),
        ),
        migrations.AddField(
            model_name='characters',
            name='character_realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Realms'),
        ),
    ]
