# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factions',
            name='id',
        ),
        migrations.AlterField(
            model_name='factions',
            name='faction_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
