# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0003_auto_20170318_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_net_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timezones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrv', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=100)),
                ('offset', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'timezones',
                'verbose_name_plural': 'Timezone Listings',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='characters',
            name='character_battle_net_id',
        ),
        migrations.AddField(
            model_name='characters',
            name='character_owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BattleNetIDs',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_timezone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Timezones'),
        ),
    ]
