# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_delete_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersdetails',
            name='character_class',
        ),
        migrations.RemoveField(
            model_name='charactersdetails',
            name='character_faction',
        ),
        migrations.RemoveField(
            model_name='charactersdetails',
            name='character_link',
        ),
        migrations.RemoveField(
            model_name='charactersdetails',
            name='character_race',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_timezone',
        ),
        migrations.AddField(
            model_name='characters',
            name='alt_role',
            field=models.CharField(blank=True, choices=[('MELEE_DPS', 'Melee DPS'), ('RANGED_DPS', 'Ranged DPS'), ('TANK', 'Tank'), ('HEALER', 'Healer'), ('NO_ROLE_SELECTED', 'No Role Selected')], default='NO_ROLE_SELECTED', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='character_armory_url_advanced',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='character_armory_url_simple',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='character_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='players.Classes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='character_faction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='players.Factions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='character_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='character_profile_avatar_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='character_profile_image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='character_profile_inset_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='character_race',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='players.Races'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='looking_for_guild',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='characters',
            name='looking_for_guild_advertisement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='main_role',
            field=models.CharField(blank=True, choices=[('MELEE_DPS', 'Melee DPS'), ('RANGED_DPS', 'Ranged DPS'), ('TANK', 'Tank'), ('HEALER', 'Healer'), ('NO_ROLE_SELECTED', 'No Role Selected')], default='NO_ROLE_SELECTED', max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='CharactersDetails',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
