# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20170320_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'regions',
                'verbose_name_plural': 'Regions',
                'ordering': ['region_name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='characters',
            name='character_region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='players.Regions'),
            preserve_default=False,
        ),
    ]
