# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_characters_is_character_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='equipped_ilevel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='max_ilevel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
