# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_profile_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timezones',
            name='offset',
        ),
    ]
