# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_timezones_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='looking_for_guild',
            field=models.BooleanField(default=False),
        ),
    ]
