# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_profile_looking_for_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='battle_net_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
