# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20170321_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'class_ability_types',
                'managed': True,
                'verbose_name_plural': 'Class Ability Types',
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='class_abilities',
            field=models.ManyToManyField(to='players.Abilities'),
        ),
    ]
