# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20170322_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='class_abilities',
        ),
        migrations.DeleteModel(
            name='Abilities',
        ),
    ]
