# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_auto_20170322_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='id',
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
