# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_auto_20170322_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={},
        ),
        migrations.RemoveField(
            model_name='classes',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='class_name',
        ),
        migrations.AddField(
            model_name='classes',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='classes',
            table=None,
        ),
    ]
