# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_auto_20170322_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'managed': True, 'verbose_name_plural': 'Character Classes'},
        ),
        migrations.AddField(
            model_name='classes',
            name='blizzard_class_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='class_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='classes',
            table='classes',
        ),
    ]
