# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_auto_20170322_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('blizzard_class_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Character Classes',
                'db_table': 'classes',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='characters',
            name='character_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='players.Classes'),
            preserve_default=False,
        ),
    ]
