# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_auto_20170322_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'managed': True, 'ordering': ['class_name'], 'verbose_name_plural': 'Character Classes'},
        ),
    ]
