# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_auto_20170322_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='load_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
