# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_auto_20170322_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Timezones'),
        ),
    ]
