# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0021_auto_20170322_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='battle_net_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
