# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_auto_20170322_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='character_profile_avatar_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='character_profile_image_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='character_profile_inset_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
