# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_auto_20170323_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='character_profile_avatar_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='characters',
            name='character_profile_image_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='characters',
            name='character_profile_inset_url',
            field=models.CharField(max_length=100),
        ),
    ]
