# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_auto_20170323_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for_guild_advertisement',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
