# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_auto_20170323_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharactersDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_level', models.IntegerField()),
                ('character_armory_url', models.URLField()),
                ('character_profile_image_url', models.CharField(max_length=100)),
                ('character_profile_avatar_url', models.CharField(max_length=100)),
                ('character_profile_inset_url', models.CharField(max_length=100)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Classes')),
            ],
            options={
                'verbose_name_plural': 'Character Details',
                'db_table': 'characters_details',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='characters',
            old_name='load_date',
            new_name='insert_date',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='character_armory_url',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='character_class',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='character_level',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='character_profile_avatar_url',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='character_profile_image_url',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='character_profile_inset_url',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='character_race',
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for_guild_advertisement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charactersdetails',
            name='character_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Characters'),
        ),
        migrations.AddField(
            model_name='charactersdetails',
            name='character_race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Races'),
        ),
    ]
