# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0026_auto_20170323_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersdetails',
            name='character_link',
        ),
        migrations.AddField(
            model_name='characters',
            name='character_details_link',
            field=models.ManyToManyField(to='players.CharactersDetails'),
        ),
    ]
