# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0027_auto_20170323_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='character_details_link',
        ),
        migrations.AddField(
            model_name='charactersdetails',
            name='character_link',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='players.Characters'),
            preserve_default=False,
        ),
    ]
