# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0028_auto_20170323_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersdetails',
            name='character_armory_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersdetails',
            name='character_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Classes'),
        ),
        migrations.AlterField(
            model_name='charactersdetails',
            name='character_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactersdetails',
            name='character_profile_avatar_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charactersdetails',
            name='character_profile_image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charactersdetails',
            name='character_profile_inset_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charactersdetails',
            name='character_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Races'),
        ),
    ]
