# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0029_auto_20170323_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='looking_for_guild',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='looking_for_guild_advertisement',
        ),
        migrations.AddField(
            model_name='charactersdetails',
            name='looking_for_guild',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersdetails',
            name='looking_for_guild_advertisement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
