# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0030_auto_20170323_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersdetails',
            name='is_my_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='characters',
            unique_together=set([('character_name', 'character_realm')]),
        ),
        migrations.AlterUniqueTogether(
            name='charactersdetails',
            unique_together=set([('character_link', 'is_my_main')]),
        ),
    ]
