# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0032_auto_20170323_1857'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characters',
            unique_together=set([('character_owner', 'character_realm', 'is_my_main')]),
        ),
    ]
