# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0033_auto_20170323_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='is_my_main',
        ),
        migrations.AlterUniqueTogether(
            name='characters',
            unique_together=set([('character_owner', 'character_name', 'character_realm', 'character_faction')]),
        ),
    ]
