# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0033_auto_20170323_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timezones',
            old_name='abbrv',
            new_name='short_name',
        ),
        migrations.AlterUniqueTogether(
            name='characters',
            unique_together=set([('character_owner', 'character_name', 'character_realm', 'character_faction')]),
        ),
    ]
