# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0034_auto_20170324_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='is_my_main',
            field=models.BooleanField(),
        ),
    ]
