# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0035_auto_20170324_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='is_my_main',
        ),
    ]
